import Head from "next/head";
import Image from "next/image";
import { ThemeProvider } from "styled-components";
import { Button } from "antd";
import Typist from "react-typist"; //animate text

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button type="primary">ding</Button>
        <Typist>Typist</Typist>
      </main>

      <footer></footer>
    </div>
  );
}
